### ISSUE TITLE
刚开始用VUE，下面报错是什么原因导致的？求解答！！

### ISSUE THREAD

**Issue by huangke2011** [gaohongwei11/vuecommunity#2]
huangke3@CND5241ZL2- MINGW64 /e/vuecommunity (master)
$ npm run start

> VueCommunity@1.0.0 start E:\vuecommunity
> node build/dev-server.js

> Starting dev server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8090
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at EventEmitter.listen (E:\vuecommunity\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (E:\vuecommunity\build\dev-server.js:84:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! VueCommunity@1.0.0 start: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the VueCommunity@1.0.0 start script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the VueCommunity package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs VueCommunity
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls VueCommunity
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huangke3\AppData\Roaming\npm-cache\_logs\2017-05-12T02_52_40_575Z-debug.log

**Comment by gaohongwei11** [comment]
Error: listen EADDRINUSE :::8090  
8090端口被占用，建议换一个端口

**Comment by gaohongwei11** [comment]
@huangke2011 
Error: listen EADDRINUSE :::8090
8090端口被占用，建议换一个端口

**Comment by Hxvin** [comment]
修改成可用的端口还是不行。
 ERROR  Failed to compile with 1 errors                                 17:03:37

This dependency was not found:

* vue-infinite-scroll in ./src/main.js

To install it, you can run: npm install --save vue-infinite-scroll
> Listening at http://localhost:8080

我根据提示run了npm install --save vue-infinite-scroll  之后没报错了 ，可是页面是空白的。怎么回事呢？？

**Comment by gaohongwei11** [comment]
抱歉刚刚看到。
npm run dev 后，URL地址：localhost:8090/vuecommunitytest。这样就可以正常显示了。
----- 原始邮件 -----
发件人：Hxvin <notifications@github.com>
收件人：gaohongwei11/vuecommunity <vuecommunity@noreply.github.com>
抄送人：GHW <gaohongwei931011@sina.com>,  Comment <comment@noreply.github.com>
主题：Re:_[gaohongwei11/vuecommunity]_刚开始用VUE，下面报错是什么原因导致的？求解答！！_(#2)
日期：2017年05月20日 17点06分

修改成可用的端口还是不行。

ERROR  Failed to compile with 1 errors                                 17:03:37
This dependency was not found:

vue-infinite-scroll in ./src/main.js

To install it, you can run: npm install --save vue-infinite-scroll

Listening at http://localhost:8080

我根据提示run了npm install --save vue-infinite-scroll  之后没报错了 ，可是页面是空白的。怎么回事呢？？

&mdash;
